package org.openvisko.module;
import org.openvisko.module.operators.SimulationOperator;
import org.openvisko.module.util.CommandRunner;
import org.openvisko.module.util.AbstractOperatorFileUtils;


public class H5WriteMesh extends SimulationOperator
{
	
	// the output name for the dataset generated by this operator
	private static final String outputFileName = "OutputMesh.xmf";
	
	public H5WriteMesh(String contextURL) {
		super(contextURL, outputFileName);
	}

	/*
	 * This method accesses the functionality of the wrapped executable. In this example, the exectuable takes
	 * three params (param1, param2, and param3). You can extend this to take as many parameters as necessary. This
	 * examples assume that the executable takes an input file path and an output file path, where the result will be written.
	 */
	public String transform()
	{
		String FileNameRandomString = AbstractOperatorFileUtils.getRandomString();
		String h5FileName = "Mesh" + FileNameRandomString + ".h5";
		String xmfFileName = "Mesh" + FileNameRandomString + ".xmf";
		
		//The command string that will be passed to the shell
		String cmd = "/share/apps/cmmf/h5WriteMesh " + h5FileName;
		CommandRunner.run(cmd, AbstractOperatorFileUtils.getWorkspace());
		
		cmd = "/share/apps/cmmf/h5WriteXmfMesh " + h5FileName + " " + xmfFileName; 
		CommandRunner.run(cmd, AbstractOperatorFileUtils.getWorkspace());

		return AbstractOperatorFileUtils.getOutputURLPrefix() + xmfFileName;
	}
}
