package org.openvisko.module;

import org.openvisko.module.registration.AbstractModuleRDFRegistration;


public class ModuleRDFRegistration extends AbstractModuleRDFRegistration {

  @Override
  public void populateViewerSets() {
    // TODO Auto-generated method stub
    
  }

  @Override
  public void populateToolkit() {
    // TODO Auto-generated method stub
    
  }

  @Override
  public void populateServices() {
    // TODO Auto-generated method stub
    
  }

  @Override
  public void populateParameterBindings() {
    // TODO Auto-generated method stub
    
  }

  /***
   * Child classes can override this method if they want to hard code a specific
   * URL instead of using the URL generated by the build.
   * @see org.openvisko.module.registration.AbstractModuleRDFRegistration#getWSDLURL()
   */
  @Override
  public String getWSDLURL() {
    //http://we20657.pnl.gov:8080/package_cii/services/PackageService?wsdl
    String wsdlUrl = getWebServerUrl() + "/" + getWebappName() + "/services/ModuleService?wsdl";
    return wsdlUrl;
  }


}
